### ISSUE TITLE
Adding a Contributors Guideline

### ISSUE THREAD

**Issue by aakankshabhende** [Ananya02850/estore#2]

**Comment by Prakash-Haldar** [comment]
I want to work in this issue under DEVINCEPT-Contribution . Please assign it to me

**Comment by Ananya02850** [comment]
Assigned

**Comment by aakankshabhende** [comment]
Mam should I work on this? @Ananya02850  as you assigned me it earlier

**Comment by Ananya02850** [comment]
@aakankshabhende yes go ahead, start working on it

**Comment by Ananya02850** [comment]
@Prakash-Haldar go ahead with different issue, this one is already assigned . We are following first come first serve rule. so please go ahead with another issue
