### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by Swastik1710** [Ananya02850/estore#4]
The website has a signup page but not a login page. I would like to add one.

**Comment by Swastik1710** [comment]
Please assign this issue to me so that I can start working on this.

**Comment by shraddhamishra611** [comment]
Can I contribute?

**Comment by harshita9621** [comment]
@Ananya02850 Can I work on this issue

**Comment by Ananya02850** [comment]
@harshita9621 yes go ahead

**Comment by Ananya02850** [comment]
@shraddhamishra611 yes please go ahead

**Comment by Ananya02850** [comment]
@Swastik1710 I had already assigned it to you

**Comment by Ananya02850** [comment]
@harshita9621 you had already been assigned with another issue, please go ahead with that
