### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by Swastik1710** [Ananya02850/estore#5]
As of now , the navbar is just fine and functional but it needs to be modified as it is the first thing a user sees on a website. I would make some changes which would make it more elegant and professional looking.

**Comment by Swastik1710** [comment]
Please let me know if I can go ahead with this.

**Comment by harshita9621** [comment]
@Ananya02850 Can I work on this issue

**Comment by Ananya02850** [comment]
@harshita9621 Yes sure ,please start working on it, i have assigned the tasks to you

**Comment by Ananya02850** [comment]
@Swastik1710  yes please go ahead
