### ISSUE TITLE
CONTRIBUTION

### ISSUE THREAD

**Issue by swathi-469** [Ananya02850/estore#9]
I would like to add contribution guidelines for beginners in open source in a form of contribution.md file ..please assign this to me

**Comment by Ananya02850** [comment]
please go ahead

**Comment by swathi-469** [comment]
Mam but why did you closed ?

**Comment by Ananya02850** [comment]
you can still contribute to it, i have just closed the issue

**Comment by Ananya02850** [comment]
you can reopen it anytime and if facing any issue feel free to ping me

**Comment by swathi-469** [comment]
Ohh kk mam I am working on this issue will do my pr today

**Comment by swathi-469** [comment]
Mam, there is already a CONTRIBUTING.md file .. what to do?

**Comment by Ananya02850** [comment]
hey can you please move ahead to different issue?

**Comment by Ananya02850** [comment]
move with a different tasks

**Comment by Ananya02850** [comment]
That has been assigned to another who has came before you so move ahead with another issue please
